insert into Product (ProductName, UnitPrice) values ('Bananen 1kg', 1.99)
insert into Product (ProductName, UnitPrice) values ('Äpfel 1kg', 2.99)
insert into Product (ProductName, UnitPrice) values ('Trauben Weiß 500g', 2.49)
insert into Product (ProductName, UnitPrice) values ('Himbeeren 125g', 1.89)
insert into Product (ProductName, UnitPrice) values ('Karotten 500g', 1.19)
insert into Product (ProductName, UnitPrice) values ('Eissalat 1 Stück', 0.99)
insert into Product (ProductName, UnitPrice) values ('Zucchini 1 Stück', 0.99)
insert into Product (ProductName, UnitPrice) values ('Knoblauch 150g', 2.49)
insert into Product (ProductName, UnitPrice) values ('Joghurt 200g', 0.49)
insert into Product (ProductName, UnitPrice) values ('Butter', 2.59)